### PR TITLE
Fix typo in SessionManager's detachSession method

### PR DESCRIPTION
**Pull request by travis**
fix typo

This PR fixes bug #.

- [ ] I've added a unit test to test for potential regressions of this bug.
- [x] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Review by NSeydoux — APPROVED** [review]
Good spot :)

**Comment by NSeydoux** [comment]
Sorry this is getting a while to get merged, I would like to investigate how to run the CI on third-party contributions properly :)

**Comment by travis** [comment]
no rush on my account! I realized I'm not dependent on this, just found it while trying out the multi-session api.

**Comment by NSeydoux** [comment]
Superceeded by https://github.com/inrupt/solid-client-authn-js/pull/349.

**Pull request closed without merging**
