### PR TITLE
Chore/1x rebase

### PR DESCRIPTION
**Pull request by NSeydoux**
This PR applies to the master branch all the changes that applied to the `1.x` branch since they diverged. Each individual commit has been reviewed except for the resolution of the merge conflicts, so this PR isn't really meant to be reviewed manually, the idea is rather to run the CI and the manual tests in the sandbox so that we can merge it back into master.

### CODE REVIEW

**Comment by NSeydoux** [comment]
The client registration and DPoP auth work against both ESS and NSS, so everything looks like it has been successfully merged. I'm not sure what's up with the Vercel deployment.

**Comment by Vinnl** [comment]
@ajacksified Could you give Nicolas access to the Vercel project?

@NSeydoux I'm not sure exactly what the Vercel error is (it complains about a package.json and lockfile being out of sync somewhere, but `npm ci` does seem to work in other checks) as I haven't been able to reproduce it locally, but `npm run build-demo-app` does fail for me in the current branch due to a missing package.json for demoClientApp?

**Comment by NSeydoux** [comment]
Ah, that looks like the demo app was lost during the merge battle. I'll re-put it in.

**Review by Vinnl — APPROVED** [review]
Cool, Vercel deployment seems to succed. I don't have credentials to ESS to verify that [the demo app](https://solid-client-authn-js-hpdkstw6s.vercel.app/demo/) works - although I suppose the e2e tests are now running successfully and verifying that?

**Comment by NSeydoux** [comment]
I haven't created a Gluu account yet, but if you use `https://broker.demo-ess.inrupt.com/` as an IdP you can log in with Google.

**Pull request merged**
