### PR TITLE
Fix outdated browser example lockfiles

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
See the individual commits for details, this bumps a bunch of outdated dependencies in the examples, upgrades the lockfiles to v2, and fixes a bug in the demoSingleApp's functionality.

### CODE REVIEW

**Review by matthieubosquet — APPROVED** [review]
LGTM

**Comment by NSeydoux** [comment]
Do you think it'd be worth enabling dependabot for these while we're at it ?

**Comment by ThisIsMissEm** [comment]
> Do you think it'd be worth enabling dependabot for these while we're at it ?
> 
> PS: some of the browser tests failing is fine, it comes from testcafé's falkiness, I'll move them to playwright soon to fix this)

Maybe, but I'm not sure the effect that'd have on our workload, so I'd perhaps be hesitant to enable it, given these are react apps and such that more frequently probably receive updates.

**Comment by ThisIsMissEm** [comment]
Just a heads up: the demoClientApp is still broken due to it's implementation (the IdP is not persisted across page loads, which means you can't actually test the client works with different IdP's in e2e tests).

**Pull request closed without merging**
